select p.a1, ttt.OrgP_Id, ttt.grado
-- update ttt set ttt.grado = p.a1
from(values
(6, 'COORDINADOR DE CENTRO DE CONTROL DE OPERACIONES'),
(6, 'TRAINEE DE MEDIO AMBIENTE'),
(6, 'AUXILIAR DE ALMACEN'),
(6, 'AUXILIAR DE HOTELERIA'),
(6, 'AUXILIAR DE MANTENIMIENTO MENOR'),
(6, 'AYUDANTE CARGADOR DE TALADROS LARGOS'),
(6, 'AYUDANTE DE MANTENIMIENTO MECANICO'),
(6, 'AYUDANTE DE PERFORACION DIAMANTINA'),
(6, 'AYUDANTE DE PLANTA'),
(6, 'AYUDANTE DE TOPOGRAFIA'),
(6, 'AYUDANTE JUMBO'),
(6, 'AYUDANTE MUESTRERO'),
(6, 'AYUDANTE SSOMA'),
(6, 'CONDUCTOR'),
(6, 'PREPARADOR DE MUESTRAS'),
(7, 'AYUDANTE MINA'),
(7, 'MUESTRERO ACOPIO'),
(7, 'OPERADOR DE PLANTA'),
(7, 'OPERADOR DE PLANTA ACOPIO'),
(7, 'TIMBRERO'),
(8, 'TECNICO DE LABORATORIO QUIMICO'),
(8, 'BALANCERO'),
(8, 'CARGADOR DISPARADOR DE TALADROS LARGOS'),
(8, 'MAESTRO MINA'),
(8, 'MUESTRERO'),
(8, 'OPERADOR CARGADOR FRONTAL'),
(8, 'OPERADOR DE EQUIPO PESADO'),
(8, 'OPERADOR LIDER'),
(8, 'WINCHERO'),
(9, 'TECNICO DE MANTENIMIENTO'),
(9, 'TECNICO DE MANTENIMIENTO ELECTRICO'),
(9, 'TECNICO DE MANTENIMIENTO MECANICO'),
(9, 'TECNICO DE MANTENIMIENTO MECANICO TRACKLES'),
(9, 'TECNICO DE MANTENIMIENTO MECANICO SOLDADOR'),
(9, 'TECNICO LINIERO'),
(9, 'TECNICO MECANICO NIVEL 3'),
(9, 'MAESTRO DE PERFORACION DIAMANTINA'),
(9, 'OPERADOR DE SCOOP A'),
(9, 'OPERADOR DE SCOOP B'),
(10, 'PARAMEDICO'),
(10, 'TRABAJADOR SOCIAL JR'),
(10, 'CAPATAZ DE PIQUE'),
(10, 'OPERADOR DE JUMBO DE TALADROS LARGOS A'),
(10, 'OPERADOR DE JUMBO DE TALADROS LARGOS B'),
(10, 'TOPOGRAFO'),
(11, 'ASISTENTE ADMINISTRATIVO'),
(11, 'ASISTENTE DE LABORATORIO QUIMICO'),
(11, 'ASISTENTE DE PROCESOS SIG'),
(11, 'ASISTENTE DE TI'),
(11, 'INGENIERO JR DE PLANEAMIENTO'),
(11, 'INGENIERO JR DE VENTILACION'),
(11, 'INSPECTOR DE SEGURIDAD'),
(12, 'ANALISTA DE GESTION HUMANA'),
(12, 'COORDINADOR DE TI'),
(12, 'INGENIERO JR DE MANTENIMIENTO'),
(12, 'INGENIERO JR DE GEOMECANICA Y GEOTECNIA'),
(12, 'SUPERVISOR DE ALMACEN'),
(12, 'SUPERVISOR DE PROTECCION PATRIMONIAL'),
(12, 'SUPERVISOR DE SERVICIOS GENERALES'),
(12, 'TRABAJADOR SOCIAL'),
(13, 'ADMINISTRADOR'),
(13, 'ASISTENTE DE ACOPIO'),
(13, 'COORDINADOR DE DESARROLLO ECONOMICO'),
(13, 'COORDINADOR DE EMERGENCIAS'),
(13, 'ESPECIALISTA DE ASUNTOS SOCIALES'),
(13, 'INGENIERO DE MEDIO AMBIENTE'),
(13, 'INGENIERO DE SEGURIDAD'),
(13, 'INSTRUCTOR'),
(13, 'JEFE DE GUARDIA PLANTA'),
(13, 'JEFE DE LABORATORIO QUIMICO'),
(13, 'JEFE DE SERVICIOS GENERALES'),
(13, 'PSICOLOGO'),
(13, 'SUPERVISOR DE MANTENIMIENTO ELECTRICO'),
(13, 'SUPERVISOR DE MANTENIMIENTO MECANICO'),
(13, 'SUPERVISOR DE METALURGIA'),
(13, 'SUPERVISOR MECANICO DE PLANTA'),
(14, 'INGENIERO DE PLANEAMIENTO'),
(14, 'INGENIERO DE COSTOS'),
(14, 'INGENIERO DE GEOMECANICA Y GEOTECNIA'),
(14, 'INGENIERO PREDICTIVO'),
(14, 'JEFE DE ACOPIO'),
(14, 'JEFE DE ALMACEN'),
(14, 'JEFE DE GESTION SOCIAL'),
(14, 'MEDICO OCUPACIONAL'),
(14, 'PLANNER SENIOR DE MANTENIMIENTO'),
(15, 'ABOGADO SENIOR'),
(15, 'ASISTENTE DE SUPERINTENDENCIA MINA'),
(15, 'GEOLOGO DE MINA'),
(15, 'GEOLOGO DE MINA Y MODELAMIENTO'),
(15, 'JEFE DE COSTOS'),
(15, 'JEFE DE GEOMECANICA Y GEOTECNIA'),
(15, 'JEFE DE MANTENIMIENTO ELECTRICO'),
(15, 'JEFE DE MANTENIMIENTO MINA'),
(15, 'JEFE DE MANTENIMIENTO PLANTA'),
(15, 'JEFE DE MEDIO AMBIENTE'),
(15, 'JEFE DE PLANTA'),
(15, 'JEFE DE PROCESOS Y SIG'),
(15, 'JEFE DE SSOMA'),
(15, 'JEFE DE VENTILACION Y SERVICIOS'),
(15, 'JEFE DE ZONA MINA'),
(16, 'JEFE DE GESTION HUMANA'),
(16, 'SUPERINTENDENTE DE ACOPIO'),
(16, 'SUPERINTENDENTE DE MEDIO AMBIENTE'),
(16, 'SUPERINTENDENTE DE SISTEMAS DE INNOVACION SOCIAL'),
(17, 'SUPERINTENDENTE DE GEOLOGIA'),
(17, 'SUPERINTENDENTE DE MANTENIMIENTO'),
(17, 'SUPERINTENDENTE DE MINA'),
(17, 'SUPERINTENDENTE DE PLANEAMIENTO'),
(17, 'SUPERINTENDENTE DE PLANTA'),
(18, 'GERENTE DE MINA'),
(18, 'GERENTE DE OPERACIONES'),
(18, 'GERENTE DE SSOMA')
)p(a1,a2)
cross apply(select*from dbo.m_Puestos pp where pp.Pues_Nombre = p.a2)pp
cross apply dbo.A10_Proyectos t
cross apply dbo.RH00_OrganigramaCab tt
cross apply dbo.RH00_OrganigramaPuestos ttt
where  pp.Pues_Id = ttt.Pues_Id and
t.proy_id = tt.proy_id and tt.Org_Id = ttt.Org_Id and
t.proy_id = 1655419281410  -- ANTAPITE


select*from dbo.RH00_OrganigramaPuestos where not grado is null


select*from dbo.m_Nivel_Posicion
select*from dbo.m_Escala_Likert
select*from dbo.RH00_OrganigramaPuestos
return
-- select*from dbo.m_Puestos
select*from dbo.m_Nivel_Posicion

-- insert into dbo.m_Diccionarios
-- select 19, 13, 'CM1', 'AGILIDAD MENTAL',
-- '¿Propone soluciones prácticas ante problemas cotidianos?',
-- 'CM', 'EA', 1, 4, getdate(), null, null, 1


select*from dbo.mastertablas
select*from dbo.masterAudit
select*from dbo.m_Nivel_Posicion
select*from dbo.m_Escala_Likert

-- select*from dbo.mastertable('dbo.m_Diccionarios')

select*from dbo.m_Diccionarios
select*from dbo.m_Diccionarios_ComGrupos
select*from dbo.m_DiccionariosTipos

set rowcount 30
-- select*from dbo.m_Puestos
select*from dbo.RH00_OrganigramaPuestos
select*from dbo.RH30_Trabajadores


-- insert into dbo.mastertablas
-- select 'dbo.m_Diccionarios'
